### ISSUE TITLE
Use custom JSONEncoder / JSONDecoder on json decorators

### ISSUE THREAD

**Issue by dhait** [dschep/lambda-decorators#9]
When pulling data from a database (using PynamoDB, for example) we are often left with a "model" object which can not be directly serialized with json, unless a custom JSONEncoder is written.  Normally we pass this class in to the json.dumps() function.

It would be extremely useful to pass this special Encoder into the dump_json_body and similar decorators

**Comment by dschep** [comment]
See https://github.com/dschep/lambda-decorators/commit/5d6891f70483ee2d78ef023331677ed8a9619e61 which i'll release soon.
